[package]
name = "fubun-linux-adapter"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[[bin]]
name = "fubun-linux-adapter"
path = "src/main.rs"

[dependencies]
fubun-domain.workspace = true
fubun-protocol.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
uuid.workspace = true

[lints]
workspace = true
